# Generated by Django 4.0.6 on 2024-08-23 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('autor', models.CharField(max_length=120)),
                ('ano', models.CharField(max_length=4)),
                ('capa', models.ImageField(upload_to='')),
                ('lido', models.BooleanField(default=False)),
                ('emprestado', models.BooleanField(default=False)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devolvido', models.BooleanField(default=False)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervodigital.contato')),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acervodigital.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario'),
        ),
    ]
