# Generated by Django 4.0.6 on 2024-09-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acervodigital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='lido',
        ),
    ]
