# Generated by Django 4.0.6 on 2024-09-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervodigital', '0003_alter_livro_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario'),
            preserve_default=False,
        ),
    ]
