# Generated by Django 4.0.6 on 2024-09-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acervodigital', '0004_contato_usuario_livro_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acervodigital.usuario'),
            preserve_default=False,
        ),
    ]
